src/d3.flameGraph.js
When tooltips are active, the browser displays a native hover based on the title attribute at the same time the d3 tooltip is displayed, leading to two tooltips at once. Suppress DOM title tags when tooltips are in use.
=> Disable SVG titles when tooltips are active

src/d3.flameGraph.js
The JS calls a setDetails function when hovering over a frame, which looks for a div of type details. If that div does not actually exist, it still tries to set innerHTML on it anyway, which fails. (spiermar/d3-flame-graph#41)
=> Don't assume an element with id details exists

src/d3.flameGraph.css, src/d3.flameGraph.js
Styles for generic elements like rect apply only under .d3-flame-graph,
and d3-tip style renamed to more specific d3-flame-graph-tip. This
should prevent conflicts with other styles set by user apps and should fix spiermar/d3-flamegraph#37.
=> Isolate styles under d3-flame-graph "namespace"

README.md, example/index.html, src/d3.flameGraph.js
This PR adds a `resetZoom` method to the `flamegraph` object. It also adds a reset zoom button to the   example.
=> Add functionality for resetting the zoom level

src/d3.flameGraph.js
Returns the search results as a list for further manipulation.
The zoomTo method is functionally the same as clicking on a frame. One use case is to zoom to a search result.
For an example see http://bl.ocks.org/kjellmf/raw/533df0ddfb0a3247275f/ (http://bl.ocks.org/kjellmf/533df0ddfb0a3247275f)
=> Make chart.search(..) return the search results + add zoomTo method

src/d3.flameGraph.js
In some cases we may want to view the flame chart in a reversed direction. ex. profiler of chrome dev tools.
=> added a configuration parameter allowing to draw graph in top-down direction

src/d3.flameGraph.js
When compiling with closure, found this single error.
```
ERROR - variable term is undeclared
clear(child, term);
^
```
=> Fix for an apparent copy/paste error in clear()

src/d3.flameGraph.js
Having the comparator return 0 when sort==false isn't a no-op because
Array.sort isn't stable. This meant sort=false could rearrange nodes.
=> don't call sort when sort==false

src/d3.flameGraph.js
Per the docs, calling tooltip with a falsy value should disable them, so the 'tooltip' variable should be false.
(Because tooltips are enabled by default, they're currently impossible to disable!)
=> Fix tooltip(false) to disable tooltips.

src/flamegraph.js
when i use the npm to install the version @3.1.0 and the 'd3-tip@0.9.1'
i found the error the same as [#231](https://github.com/caged/d3-tip/issues/231)
so i try 2 fix it
=> fix: 'targetel.getScreenCTM is not a function' error with 'd3-tip@0.9.1'

README.md, src/flamegraph.js
Added an optional boolean argument for the function searchMatch. If the argument is true, then only, the search will be case-sensitive. By default if no argument is passed during the function call, the argument will be set to false.
Made the necessary changes in the README file as well.
=> Fixes issue #144 - Ignore Case on Search

.eslintrc.json, babel.config.json, jest.config.js, package-lock.json, package.json, src/templates/base/template.html, test/flamegraph.js, webpack.config.js
The tests run with nodejs, which doesn't support ES6 modules - therefore I had to include babel to precompile the tests. Babel isn't used in the main compilation (webpack supports ES6 modules natively).
=> unit tests using jest snapshots

src/colorMapper.js, src/colorScheme.js, src/colorUtils.js, src/flamegraph.js, src/templates/base/template.css, src/templates/base/template.html, src/templates/base/template.js
* customizable color scheme (`blue-green` to improve accessibility, with fallback to default orange colors)
* option to show context/environment information (if available, for example to show the `perf.data` header in the `flamegraph.html` file, see https://lkml.org/lkml/2021/8/30/668)
This is a backwards compatible change.
=> template improvements (color scheme/accessibility, show context information)

index.d.ts
I've added a third overload for `sort` to the type definitions.  This definition allows passing in a comparator function.
You can see an example of this in the [existing examples](https://github.com/spiermar/d3-flame-graph/blob/58c370ec1bcab133816a7a1a0ba8245af7f4db98/examples/index.html#L88).  While this works fine, the TypeScript definitions only allowed for passing no args or a boolean in.
You will notice this is a simple comparator function, similar to those used by d3 array in [its type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b5754e3f45e359659161985f82de974721b336d8/types/d3-array/index.d.ts#L990).  Notice that I've bound the generic variable `T` here to `StackFrame`.  I'm not 100% sure that's correct.  If other things besides `StackFrame`s could be …
=> Allow passing comparators to flamegraph.sort

README.md
So they display as code, rather than plain-text, all run-together on one line.
=> Quote some code blocks in the README

README.md, src/flamegraph.js, src/templates/base/template.js, test/flamegraph.js
This commit series makes loading untrusted profiles safer, by not executing their contents as HTML on mouseover.
And it also updates the search handler, which had a safe default, but encouraged users in the README to use `.innerHTML`, which is less safe.
I had to look up whether to use `.innerText` or `.textContent`.
I used `.textContent` here as that's what `d3.text` uses: https://github.com/d3/d3-selection/blob/464cb9a0af622375fee526ebbb66f709d5d92a2b/src/selection/text.js#L7, and that seemed like a good precedent.
=> HTML-escape contents of the details element

README.md, examples/index.html, src/tooltip.js, test/flamegraph.js
This commit series makes loading untrusted profiles safer, by not executing their contents as HTML on mouseover.
This follows https://github.com/spiermar/d3-flame-graph/pull/200, and has the same motivation.
=> HTML-escape contents of the tooltip element

src/tooltip.js
I accidentally inlined these in a previous commit, thinking if they were in the same d3 chain of methods, it would be a no-op.
But the .transition().duration(200) makes these properties animate, leading to a funny dance where the tooltip chases the pointer, 200ms behind.
Moving these property setting before the transition() fixes the problem.
I didn't notice this in my testing because I was only running with a tiny flamegraph with one node to check the HTML escaping!
=> Don't animate left & top of tooltip

README.md
Tiny doc update to expose the up-to-date colours in [colorScheme.js](https://github.com/spiermar/d3-flame-graph/blob/master/src/colorScheme.js)
=> Update README with all palettes in colorScheme.js

README.md
I used this recently with some JSON where I couldn't easily add a `name` key.
=> Add README docs for flamegraph.getName
